/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrintingRouteImport } from './routes/printing'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminImportsRouteImport } from './routes/admin.imports'
import { Route as AdminGmailRouteImport } from './routes/admin.gmail'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'
import { Route as AdminAcademicYearsRouteImport } from './routes/admin.academic-years'

const PrintingRoute = PrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/admin/subjects',
  path: '/admin/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/admin/sessions',
  path: '/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportsRoute = AdminImportsRouteImport.update({
  id: '/admin/imports',
  path: '/admin/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGmailRoute = AdminGmailRouteImport.update({
  id: '/admin/gmail',
  path: '/admin/gmail',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/admin/assignments',
  path: '/admin/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcademicYearsRoute = AdminAcademicYearsRouteImport.update({
  id: '/admin/academic-years',
  path: '/admin/academic-years',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/printing': typeof PrintingRoute
  '/admin/academic-years': typeof AdminAcademicYearsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/gmail': typeof AdminGmailRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/printing': typeof PrintingRoute
  '/admin/academic-years': typeof AdminAcademicYearsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/gmail': typeof AdminGmailRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/printing': typeof PrintingRoute
  '/admin/academic-years': typeof AdminAcademicYearsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/gmail': typeof AdminGmailRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/dashboard'
    | '/login'
    | '/pending'
    | '/printing'
    | '/admin/academic-years'
    | '/admin/assignments'
    | '/admin/gmail'
    | '/admin/imports'
    | '/admin/sessions'
    | '/admin/subjects'
    | '/admin/users'
    | '/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/dashboard'
    | '/login'
    | '/pending'
    | '/printing'
    | '/admin/academic-years'
    | '/admin/assignments'
    | '/admin/gmail'
    | '/admin/imports'
    | '/admin/sessions'
    | '/admin/subjects'
    | '/admin/users'
    | '/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/dashboard'
    | '/login'
    | '/pending'
    | '/printing'
    | '/admin/academic-years'
    | '/admin/assignments'
    | '/admin/gmail'
    | '/admin/imports'
    | '/admin/sessions'
    | '/admin/subjects'
    | '/admin/users'
    | '/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  PrintingRoute: typeof PrintingRoute
  AdminAcademicYearsRoute: typeof AdminAcademicYearsRoute
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminGmailRoute: typeof AdminGmailRoute
  AdminImportsRoute: typeof AdminImportsRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/printing': {
      id: '/printing'
      path: '/printing'
      fullPath: '/printing'
      preLoaderRoute: typeof PrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/admin/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/imports': {
      id: '/admin/imports'
      path: '/admin/imports'
      fullPath: '/admin/imports'
      preLoaderRoute: typeof AdminImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gmail': {
      id: '/admin/gmail'
      path: '/admin/gmail'
      fullPath: '/admin/gmail'
      preLoaderRoute: typeof AdminGmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/admin/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/academic-years': {
      id: '/admin/academic-years'
      path: '/admin/academic-years'
      fullPath: '/admin/academic-years'
      preLoaderRoute: typeof AdminAcademicYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  PrintingRoute: PrintingRoute,
  AdminAcademicYearsRoute: AdminAcademicYearsRoute,
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminGmailRoute: AdminGmailRoute,
  AdminImportsRoute: AdminImportsRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
