import { ConvexError } from "convex/values";

export const ERROR_CODES = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  FORBIDDEN: "FORBIDDEN",
  CASE_NOT_FOUND: "CASE_NOT_FOUND",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  STALE_CASE_VERSION: "STALE_CASE_VERSION",
  DEADLINE_CLOSED: "DEADLINE_CLOSED",
  ASSIGNMENT_LOCKED: "ASSIGNMENT_LOCKED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  PDF_TOO_LARGE: "PDF_TOO_LARGE",
  PDF_TYPE_INVALID: "PDF_TYPE_INVALID",
  PDF_CORRUPTED: "PDF_CORRUPTED",
  PDF_ENCRYPTED: "PDF_ENCRYPTED",
  R2_UPLOAD_FAILED: "R2_UPLOAD_FAILED",
  R2_OBJECT_MISSING: "R2_OBJECT_MISSING",
  GMAIL_DISCONNECTED: "GMAIL_DISCONNECTED",
  EMAIL_DELIVERY_FAILED: "EMAIL_DELIVERY_FAILED",
  IMPORT_INVALID: "IMPORT_INVALID",
  IMPORT_CONFLICT: "IMPORT_CONFLICT",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

export function throwError(code: ErrorCode, message?: string): never {
  throw new ConvexError({
    code,
    message: message || code,
  });
}
